USE [MDMDW]
GO

/****** Object:  Table [NISC].[D_FEEDER]    Script Date: 6/21/2024 9:33:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NISC].[D_FEEDER](
	[FEEDER_NAME] [varchar](6) NOT NULL,
	[FEEDER_NBR] [varchar](3) NOT NULL,
	[SUBSTATION_TRANSFORMER_NBR] [varchar](5) NOT NULL,
	[ACTIVE_YN] [bit] NOT NULL,
	[INACTIVE_DATE_ID] [int] NULL,
 CONSTRAINT [PK_D_FEEDER] PRIMARY KEY CLUSTERED 
(
	[FEEDER_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NISC].[D_FEEDER]  WITH CHECK ADD  CONSTRAINT [FK_D_FEEDER_D_DATE] FOREIGN KEY([INACTIVE_DATE_ID])
REFERENCES [CORE].[D_DATE] ([DATE_ID])
GO

ALTER TABLE [NISC].[D_FEEDER] CHECK CONSTRAINT [FK_D_FEEDER_D_DATE]
GO

ALTER TABLE [NISC].[D_FEEDER]  WITH CHECK ADD  CONSTRAINT [FK_D_FEEDER_D_SUBSTATION_TRANSFORMER] FOREIGN KEY([SUBSTATION_TRANSFORMER_NBR])
REFERENCES [NISC].[D_SUBSTATION_TRANSFORMER] ([SUBSTATION_TRANSFORMER_NBR])
GO

ALTER TABLE [NISC].[D_FEEDER] CHECK CONSTRAINT [FK_D_FEEDER_D_SUBSTATION_TRANSFORMER]
GO

