USE [MDMDW]
GO

/****** Object:  Table [NISC].[D_SUBSTATION]    Script Date: 6/21/2024 9:33:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NISC].[D_SUBSTATION](
	[SUBSTATION_NBR] [varchar](3) NOT NULL,
	[SUBSTATION_NAME] [varchar](30) NOT NULL,
	[ACTIVE_YN] [bit] NOT NULL,
	[INACTIVE_DATE_ID] [int] NULL,
 CONSTRAINT [PK_D_SUBSTATION] PRIMARY KEY CLUSTERED 
(
	[SUBSTATION_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NISC].[D_SUBSTATION]  WITH CHECK ADD  CONSTRAINT [FK_D_SUBSTATION_D_DATE] FOREIGN KEY([INACTIVE_DATE_ID])
REFERENCES [CORE].[D_DATE] ([DATE_ID])
GO

ALTER TABLE [NISC].[D_SUBSTATION] CHECK CONSTRAINT [FK_D_SUBSTATION_D_DATE]
GO

