USE [MDMDW]
GO

/****** Object:  Table [NISC].[D_SUBSTATION_TRANSFORMER]    Script Date: 6/21/2024 9:32:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [NISC].[D_SUBSTATION_TRANSFORMER](
	[SUBSTATION_TRANSFORMER_NBR] [varchar](5) NOT NULL,
	[SUBSTATION_TRANSFORMER] [varchar](2) NOT NULL,
	[SUBSTATION_NBR] [varchar](3) NOT NULL,
	[ACTIVE_YN] [bit] NOT NULL,
	[INACTIVE_DATE_ID] [int] NULL,
 CONSTRAINT [PK_D_SUBSTATION_TRANSFORMER] PRIMARY KEY CLUSTERED 
(
	[SUBSTATION_TRANSFORMER_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [NISC].[D_SUBSTATION_TRANSFORMER]  WITH CHECK ADD  CONSTRAINT [FK_D_SUBSTATION_TRANSFORMER_D_SUBSTATION] FOREIGN KEY([SUBSTATION_NBR])
REFERENCES [NISC].[D_SUBSTATION] ([SUBSTATION_NBR])
GO

ALTER TABLE [NISC].[D_SUBSTATION_TRANSFORMER] CHECK CONSTRAINT [FK_D_SUBSTATION_TRANSFORMER_D_SUBSTATION]
GO

ALTER TABLE [NISC].[D_SUBSTATION_TRANSFORMER]  WITH CHECK ADD  CONSTRAINT [FK_SUBSTATION_TRANSFORMER_D_DATE] FOREIGN KEY([INACTIVE_DATE_ID])
REFERENCES [CORE].[D_DATE] ([DATE_ID])
GO

ALTER TABLE [NISC].[D_SUBSTATION_TRANSFORMER] CHECK CONSTRAINT [FK_SUBSTATION_TRANSFORMER_D_DATE]
GO

