USE [MDMDW]
GO

/****** Object:  Table [staging].[D_SUBSTATION_TRANSFORMER]    Script Date: 7/11/2024 1:26:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [staging].[D_SUBSTATION_TRANSFORMER](
	[SUBSTATION_NAME] [varchar](30) NOT NULL,
	[SUBSTATION_TRANSFORMER_NBR] [varchar](5) NOT NULL,
	[FEEDER_NBR] [varchar](6) NOT NULL
) ON [PRIMARY]
GO


