USE [MDMDW]
GO

/****** Object:  Table [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE]    Script Date: 7/11/2024 12:45:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE](
	[INTERVAL_READ_BY_ATTRIBUTE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[INTERVAL_END_DT_TM] [datetime] NOT NULL,
	[UOM_NBR] [int] NOT NULL,
	[AGGREGATE_ATTRIBUTE_ID] [int] NOT NULL,
	[VALUE] [float] NOT NULL,
	[METER_CNT] [int] NOT NULL,
 CONSTRAINT [PK_F_INTERVAL_READ_BY_ATTRIBUTE] PRIMARY KEY CLUSTERED 
(
	[INTERVAL_READ_BY_ATTRIBUTE_ID] ASC,
	[INTERVAL_END_DT_TM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PS_AGG_MonthWise]([INTERVAL_END_DT_TM])
) ON [PS_AGG_MonthWise]([INTERVAL_END_DT_TM])
GO

ALTER TABLE [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK_INTERVAL_READ_BY_ATTRIBUTE_D_AGGREGATE_ATTRIBUTE] FOREIGN KEY([AGGREGATE_ATTRIBUTE_ID])
REFERENCES [MDM].[D_AGGREGATE_ATTRIBUTE] ([AGGREGATE_ATTRIBUTE_ID])
GO

ALTER TABLE [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE] CHECK CONSTRAINT [FK_INTERVAL_READ_BY_ATTRIBUTE_D_AGGREGATE_ATTRIBUTE]
GO

ALTER TABLE [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE]  WITH CHECK ADD  CONSTRAINT [FK_INTERVAL_READ_BY_ATTRIBUTE_DIM_UOM] FOREIGN KEY([UOM_NBR])
REFERENCES [MDM].[DIM_UOM] ([UOM_NBR])
GO

ALTER TABLE [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE] CHECK CONSTRAINT [FK_INTERVAL_READ_BY_ATTRIBUTE_DIM_UOM]
GO

CREATE NONCLUSTERED INDEX [F_INTERVAL_READ_BY_ATTRIBUTE_IDX1] ON [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE]
(
	[AGGREGATE_ATTRIBUTE_ID] ASC,
	[UOM_NBR] ASC,
	[INTERVAL_END_DT_TM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PS_AGG_MonthWise]([INTERVAL_END_DT_TM])
GO

