USE [MDMDW]
GO

/****** Object:  View [MDM].[D_AGGREGATE_ATTRIBUTE_VIEW]    Script Date: 6/21/2024 9:35:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [MDM].[D_AGGREGATE_ATTRIBUTE_VIEW]
AS
SELECT [AGGREGATE_ATTRIBUTE_ID], [AGGREGATE_ATTRIBUTE_TYPE], [AGGREGATE_ATTRIBUTE_VALUE]
  FROM [MDM].[D_AGGREGATE_ATTRIBUTE]

GO

CREATE VIEW [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE_VIEW]
AS
SELECT [INTERVAL_READ_BY_ATTRIBUTE_ID], [INTERVAL_END_DT_TM], f.[AGGREGATE_ATTRIBUTE_ID], [VALUE], [METER_CNT], 
		uom.[UOM_NBR], uom.[UOM], uom.[DIRECTION], uom.[CHANNEL], uom.[DESCRIPTION],
			a.[AGGREGATE_ATTRIBUTE_TYPE], a.[AGGREGATE_ATTRIBUTE_VALUE], a.[AGGREGATE_ATTRIBUTE_PHASE]
  FROM [MDM].[F_INTERVAL_READ_BY_ATTRIBUTE] f 
												INNER JOIN [MDM].[DIM_UOM] uom ON f.UOM_NBR = uom.UOM_NBR
												INNER JOIN [MDM].[D_AGGREGATE_ATTRIBUTE] a ON a.[AGGREGATE_ATTRIBUTE_ID] = f.[AGGREGATE_ATTRIBUTE_ID]


GO

CREATE VIEW [NISC].[D_FEEDER_VIEW]
AS
SELECT [FEEDER_NBR], [FEEDER_NAME], [SUBSTATION_TRANSFORMER_NBR], [ACTIVE_YN], [INACTIVE_DATE_ID]
  FROM [NISC].[D_FEEDER]

GO

CREATE VIEW [NISC].[D_SUBSTATION_TRANSFORMER_VIEW]
AS
SELECT [SUBSTATION_TRANSFORMER_NBR], [SUBSTATION_TRANSFORMER], [SUBSTATION_NBR], [ACTIVE_YN], [INACTIVE_DATE_ID]
  FROM [NISC].[D_SUBSTATION_TRANSFORMER]

GO

CREATE VIEW [NISC].[D_SUBSTATION_VIEW]
AS
SELECT [SUBSTATION_NBR], [SUBSTATION_NAME], [ACTIVE_YN], [INACTIVE_DATE_ID]
  FROM [NISC].[D_SUBSTATION]

GO

CREATE VIEW [NISC].[D_METER_FILTER_VIEW]
AS
SELECT [BI_MTR_NBR], [AGGREGATE_ATTRIBUTE_TYPE]
  FROM [NISC].[D_METER_FILTER]

GO
